### ISSUE TITLE
Error On Build Webpack 4

### ISSUE THREAD

**Issue by prakasa1904** [sebhildebrandt/osx-temperature-sensor#2]
I found this error when build prod with webpack 4:

```
webpack:bundle         /Users/prakasa/Projects/tokopedia-lite-v2/anakin/node_modules/osx-temperature-sensor/build/Release/smc doesn't exist
  webpack:bundle       .js
  webpack:bundle         /Users/prakasa/Projects/tokopedia-lite-v2/anakin/node_modules/osx-temperature-sensor/build/Release/smc.js doesn't exist
  webpack:bundle       .jsx
  webpack:bundle         /Users/prakasa/Projects/tokopedia-lite-v2/anakin/node_modules/osx-temperature-sensor/build/Release/smc.jsx doesn't exist
  webpack:bundle       .json
```

**Comment by sebhildebrandt** [comment]
Hi, not sure, what you are tying to do. `osx-temperature-sensor` is supposed to be used only server side (node.js). So if you are tying to use this within a browser, this anyway will not work. 

If you are trying to use is on server side WITH webpack - I didn't know that this could work. Maybe you can give me a hint how this might work.
