### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by lu0713** [sebhildebrandt/osx-temperature-sensor#7]
Hi there! Getting the following error when trying to build - using macOS Catalina

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:

**Comment by sebhildebrandt** [comment]
@lu0713 seems that you are trying to run this in a Linux container. This will not work.

**Comment by sebhildebrandt** [comment]
@lu0713 can you give some details / context you tried to build this ... as NPM said on your machine: 

Unsupported platform ... current: {"os":"linux","arch":"x64"}

**Comment by lu0713** [comment]
Everytime I try to install a different node module, I get an error: 

osx-temperature-sensor@1.0.7 install /Users/macbook/Documents/github/chronos/Chronos/node_modules/osx-temperature-sensor
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/macbook/.nvm/versions/node/v14.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/macbook/.nvm/versions/node/v14.9.0/bin/node" "/Users/macbook/.nvm/versions/node/v14.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macbook/Documents/github/chronos/Chronos/node_modules/osx-temperature-sensor
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.0 requires a peer of eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.13.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN recoil@0.0.10 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN recoil@0.0.10 requires a peer of react-dom@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN chronos@4.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by sebhildebrandt** [comment]
@lu0713 ... your last reply seems to be another problem. Do you have XCODE installed? The error message clearly said:

```
gyp: No Xcode or CLT version detected!
```

**Comment by lu0713** [comment]
I do have xCode installed butI realized it was an error with the node-gyp and the CommandLineTools! So sorry!

**Comment by sebhildebrandt** [comment]
@lu0713  OK, closing this for now ...
